// Package games serves the admin-managed game registry
// (manifests/_registry/games.json) and the per-game icon upload.
package games

import (
	"bytes"
	"encoding/json"
	"fmt"
	"image"
	"image/jpeg"
	"image/png"
	"io"
	"log"
	"net/http"
	"os"
	"path/filepath"
	"sort"
	"strings"

	"ChillHub/server/internal/adminapi/media"
	"ChillHub/server/internal/adminutil"
)

// Entry is one record of the games registry.
type Entry struct {
	GameID          string `json:"gameId"`
	Title           string `json:"title"`
	ExeRelativePath string `json:"exeRelativePath"`
	IconURL         string `json:"iconUrl"`
	Order           int    `json:"order"`
	Pinned          bool   `json:"pinned"`
	// ThunderstoreCommunity names the Thunderstore community this game's mods
	// are published under (e.g. "lethal-company"). Empty hides the "Модпаки"
	// tab for the game — most games in the registry have no Thunderstore
	// presence at all.
	ThunderstoreCommunity string `json:"thunderstoreCommunity"`
}

// Handlers serves the games endpoints for one content root.
type Handlers struct {
	root string
}

// New returns handlers rooted at the given content directory.
func New(root string) *Handlers { return &Handlers{root: root} }

// registryPath stores the registry separately from any game ID to avoid collisions.
func (h *Handlers) registryPath() string {
	return filepath.Join(h.root, "manifests", "_registry", "games.json")
}

// FromManifests scans manifests/* and builds an initial registry list.
func (h *Handlers) FromManifests() []Entry {
	base := filepath.Join(h.root, "manifests")
	entries, err := os.ReadDir(base)
	if err != nil {
		return []Entry{}
	}
	items := make([]Entry, 0)
	for _, e := range entries {
		if !e.IsDir() {
			continue
		}
		gid := e.Name()
		name := strings.ToLower(gid)
		// Skip special/system folders that are not games
		if name == "repo" || name == "_registry" || name == "launcher" {
			continue
		}
		items = append(items, Entry{GameID: gid, Title: gid, ExeRelativePath: "", IconURL: ""})
	}
	sort.Slice(items, func(i, j int) bool { return items[i].GameID < items[j].GameID })
	return items
}

// sortEntries orders the registry the way the launcher's gallery expects it:
// pinned games first, then by the operator-assigned Order, then by GameID so
// that entries tied on both stay in a stable, predictable order instead of
// whatever order the JSON file happened to list them in.
func sortEntries(items []Entry) {
	sort.Slice(items, func(i, j int) bool {
		a, b := items[i], items[j]
		if a.Pinned != b.Pinned {
			return a.Pinned && !b.Pinned
		}
		if a.Order != b.Order {
			return a.Order < b.Order
		}
		return a.GameID < b.GameID
	})
}

// Get returns the registry, autogenerating it from the manifests on first use.
func (h *Handlers) Get(w http.ResponseWriter, _ *http.Request) {
	p := h.registryPath()
	if _, err := os.Stat(p); err != nil {
		h.serveAutogenerated(w, p)
		return
	}
	// #nosec G304 -- p is registryPath(): the content root plus three constant
	// path components. No part of it comes from the request.
	b, err := os.ReadFile(p)
	if err != nil {
		adminutil.Fail(w, http.StatusInternalServerError, "failed to read the registry", "games", err)
		return
	}
	var raw struct {
		Items []json.RawMessage `json:"items"`
	}
	if err := json.Unmarshal(b, &raw); err != nil {
		// The stored registry is malformed; hand it back as-is rather than
		// failing the request outright, matching the previous behaviour.
		w.Header().Set("Content-Type", "application/json")
		_, _ = w.Write(b)
		return
	}
	items := make([]Entry, 0, len(raw.Items))
	for i, item := range raw.Items {
		var e Entry
		if err := json.Unmarshal(item, &e); err != nil {
			continue
		}
		// Registries saved before Order/Pinned existed have neither key, and
		// both zero-value to Order=0 — indistinguishable from an entry that
		// explicitly wants position 0. Defaulting every legacy entry's Order
		// to its original position in the file (instead of leaving it at 0)
		// preserves whatever curated order was already on disk, rather than
		// every Get() silently collapsing it to alphabetical-by-GameID.
		var probe map[string]json.RawMessage
		if err := json.Unmarshal(item, &probe); err == nil {
			if _, hasOrder := probe["order"]; !hasOrder {
				e.Order = i
			}
		}
		items = append(items, e)
	}
	sortEntries(items)
	adminutil.WriteJSON(w, struct {
		Items []Entry `json:"items"`
	}{Items: items})
}

// serveAutogenerated builds the registry from manifests/{gameId}/ on first use
// and stores it: on a fresh server the panel must still list the games that
// have manifests, or it looks empty on a server that is serving games.
//
// Failing to persist is logged but not fatal — the answer is still correct and
// the next request simply regenerates it.
func (h *Handlers) serveAutogenerated(w http.ResponseWriter, p string) {
	b, err := json.MarshalIndent(struct {
		Items []Entry `json:"items"`
	}{Items: h.FromManifests()}, "", "  ")
	if err != nil {
		adminutil.Fail(w, http.StatusInternalServerError, "failed to build the registry", "games", err)
		return
	}
	// 0o755/0o644 here and below: manifests/ is the tree nginx serves straight
	// from disk, so it has to stay readable outside this process.
	if err := os.MkdirAll(filepath.Dir(p), 0o755); err != nil { // #nosec G301 -- see above
		log.Printf("[games] create registry dir: %v", err)
	} else if err := adminutil.WriteFileAtomic(p, b, 0o644); err != nil {
		log.Printf("[games] store autogenerated registry: %v", err)
	}
	w.Header().Set("Content-Type", "application/json")
	_, _ = w.Write(b)
}

// Save overwrites the registry with the posted list.
func (h *Handlers) Save(w http.ResponseWriter, r *http.Request) {
	if !adminutil.RequireMethod(w, r, http.MethodPost) {
		return
	}
	var payload struct {
		Items []Entry `json:"items"`
	}
	if err := json.NewDecoder(r.Body).Decode(&payload); err != nil {
		http.Error(w, "invalid json body", http.StatusBadRequest)
		return
	}
	// Reject a bad id HERE, not later on read.
	//
	// Every id in this file becomes a path component: the public API joins it
	// onto the manifests directory. The reader drops entries that do not pass
	// this check, but dropping is a silent cure — a typo in the id made the game
	// vanish from the launcher while the panel still reported "saved". Refusing
	// the save is the honest answer: the operator learns immediately which entry
	// is wrong instead of hunting for a game that no longer appears.
	for i, it := range payload.Items {
		if !adminutil.IsSafeGameID(it.GameID) {
			http.Error(w,
				fmt.Sprintf("entry %d: gameId must be non-empty and contain only letters, digits, '-' or '_'", i+1),
				http.StatusBadRequest)
			return
		}
	}
	b, err := json.MarshalIndent(payload, "", "  ")
	if err != nil {
		adminutil.Fail(w, http.StatusBadRequest, "failed to encode the registry", "games", err)
		return
	}
	outDir := filepath.Dir(h.registryPath())
	// 0o755/0o644: manifests/ is served straight from disk by nginx.
	if err := os.MkdirAll(outDir, 0o755); err != nil { // #nosec G301 -- see above
		adminutil.Fail(w, http.StatusInternalServerError, "failed to store the registry", "games", err)
		return
	}
	// The launcher reads this registry through the public API; a truncated write
	// would be served as-is.
	if err := adminutil.WriteFileAtomic(h.registryPath(), b, 0o644); err != nil {
		adminutil.Fail(w, http.StatusInternalServerError, "failed to store the registry", "games", err)
		return
	}
	w.Header().Set("Content-Type", "application/json")
	_, _ = w.Write(b)
}

// Scan returns the registry list derived from the manifests directory without
// touching the stored registry.
func (h *Handlers) Scan(w http.ResponseWriter, _ *http.Request) {
	adminutil.WriteJSON(w, struct {
		Items []Entry `json:"items"`
	}{Items: h.FromManifests()})
}

// IconUpload saves the uploaded image as manifests/{gameId}/icon.png and
// returns its URL.
func (h *Handlers) IconUpload(w http.ResponseWriter, r *http.Request) {
	if !adminutil.RequireMethod(w, r, http.MethodPost) {
		return
	}
	// Bound the whole request before parsing, exactly as the news asset upload
	// does: without this a client can make the process buffer and then read an
	// arbitrary amount of data.
	r.Body = http.MaxBytesReader(w, r.Body, media.MaxImageBytes+(1<<20))
	if err := r.ParseMultipartForm(16 << 20); err != nil { // 16MB
		http.Error(w, "request too large or malformed", http.StatusBadRequest)
		return
	}
	gid, ok := iconGameID(w, r)
	if !ok {
		return
	}
	data, ok := readIconUpload(w, r)
	if !ok {
		return
	}
	img, err := decodeIcon(data)
	if err != nil {
		http.Error(w, "unsupported image format", http.StatusBadRequest)
		return
	}
	// Ensure directory and save as PNG with fixed name icon.png. 0o755/0o644:
	// manifests/ is the tree nginx serves straight from disk.
	dir := filepath.Join(h.root, "manifests", gid)
	if err := os.MkdirAll(dir, 0o755); err != nil { // #nosec G301 -- see above
		adminutil.Fail(w, http.StatusInternalServerError, "failed to save icon", "games:icon", err)
		return
	}
	outPath := filepath.Join(dir, "icon.png")
	if !adminutil.EnsureWithin(filepath.Join(h.root, "manifests"), outPath) {
		http.Error(w, "invalid path", http.StatusBadRequest)
		return
	}
	if err := encodeIconPNG(outPath, img); err != nil {
		log.Printf("[games:icon] store %s: %v", outPath, err)
		http.Error(w, "failed to save icon", http.StatusInternalServerError)
		return
	}
	adminutil.WriteJSON(w, map[string]string{"status": "ok", "url": "/manifests/" + gid + "/icon.png"})
}

// iconGameID reads the gameId from the form and validates it BEFORE it is
// turned into a path: the EnsureWithin check in IconUpload used to run only
// after os.MkdirAll had already created (or traversed into) whatever directory
// the client asked for.
func iconGameID(w http.ResponseWriter, r *http.Request) (string, bool) {
	gid := strings.TrimSpace(r.FormValue("gameId"))
	if gid == "" {
		http.Error(w, "missing gameId", http.StatusBadRequest)
		return "", false
	}
	if !adminutil.IsSafeGameID(gid) {
		http.Error(w, "invalid gameId", http.StatusBadRequest)
		return "", false
	}
	return gid, true
}

// readIconUpload returns the uploaded bytes, bounded in both size and declared
// dimensions. It answers the client itself and reports ok=false.
func readIconUpload(w http.ResponseWriter, r *http.Request) ([]byte, bool) {
	file, _, err := r.FormFile("file")
	if err != nil {
		http.Error(w, "missing file", http.StatusBadRequest)
		return nil, false
	}
	defer func() { _ = file.Close() }()
	// io.ReadAll on a multipart part is unbounded by itself: the part may have
	// been spooled to disk and be far larger than the parse window, so the whole
	// file would land in RAM.
	data, err := io.ReadAll(io.LimitReader(file, media.MaxImageBytes+1))
	if err != nil {
		log.Printf("[games:icon] read upload: %v", err)
		http.Error(w, "failed to read upload", http.StatusInternalServerError)
		return nil, false
	}
	if len(data) > media.MaxImageBytes {
		http.Error(w, "image too large", http.StatusRequestEntityTooLarge)
		return nil, false
	}
	// Check the declared dimensions from the header before decoding: a tiny
	// PNG can announce 30000x30000 and cost gigabytes of pixel buffer.
	if err := media.CheckImageBounds(data); err != nil {
		http.Error(w, "image dimensions too large", http.StatusBadRequest)
		return nil, false
	}
	return data, true
}

// decodeIcon decodes PNG/JPEG. The format is not returned: the icon is always
// re-encoded as PNG.
func decodeIcon(data []byte) (image.Image, error) {
	img, _, err := image.Decode(bytes.NewReader(data))
	if err == nil {
		return img, nil
	}
	// The sniffing decoder failed; try the two supported formats explicitly.
	if im, e := png.Decode(bytes.NewReader(data)); e == nil {
		return im, nil
	}
	if im, e := jpeg.Decode(bytes.NewReader(data)); e == nil {
		return im, nil
	}
	return nil, err
}

// encodeIconPNG encodes into memory and writes atomically. os.Create truncates
// the live icon first, so a failed encode used to leave a zero-length or
// half-written file in a tree the public API serves — and the working icon was
// gone.
func encodeIconPNG(outPath string, img image.Image) error {
	var buf bytes.Buffer
	if err := png.Encode(&buf, img); err != nil {
		return err
	}
	return adminutil.WriteFileAtomic(outPath, buf.Bytes(), 0o644)
}
