package games

import (
	"encoding/json"
	"net/http"
	"net/http/httptest"
	"os"
	"path/filepath"
	"strings"
	"testing"
)

// decodeItems runs a handler and decodes the {"items":[...]} envelope every games
// endpoint answers with.
func decodeItems(t *testing.T, fn http.HandlerFunc, r *http.Request) []Entry {
	t.Helper()
	w := httptest.NewRecorder()
	fn(w, r)
	if w.Code != http.StatusOK {
		t.Fatalf("handler returned %d: %s", w.Code, w.Body.String())
	}
	var out struct {
		Items []Entry `json:"items"`
	}
	if err := json.Unmarshal(w.Body.Bytes(), &out); err != nil {
		t.Fatalf("body is not the items envelope: %v (%s)", err, w.Body.String())
	}
	return out.Items
}

// withManifestDirs creates manifests/<name>/ for each name and returns the root.
func withManifestDirs(t *testing.T, names ...string) string {
	t.Helper()
	root := t.TempDir()
	for _, n := range names {
		if err := os.MkdirAll(filepath.Join(root, "manifests", n), 0o750); err != nil {
			t.Fatal(err)
		}
	}
	return root
}

// The registry is what the launcher's game list is built from. On a fresh server
// it does not exist yet, and the admin must still see the games that have
// manifests — otherwise the panel looks empty on a server that is serving games.
func TestGetAutogeneratesRegistryOnFirstUse(t *testing.T) {
	root := withManifestDirs(t, "lethal-company", "raft")
	h := New(root)

	items := decodeItems(t, h.Get, httptest.NewRequestWithContext(t.Context(), http.MethodGet, "/admin/api/games", nil))
	if len(items) != 2 {
		t.Fatalf("autogenerated registry holds %d games, want 2: %+v", len(items), items)
	}

	// It must also be persisted: the admin edits titles and paths on top of it.
	if _, err := os.Stat(filepath.Join(root, "manifests", "_registry", "games.json")); err != nil {
		t.Fatalf("the autogenerated registry was not written: %v", err)
	}
}

// Service directories are not games. 'launcher' in particular holds the launcher's
// own build manifests — listing it would put the launcher into its own game list.
func TestServiceDirectoriesAreNotGames(t *testing.T) {
	h := New(withManifestDirs(t, "launcher", "repo", "_registry", "real-game", "LAUNCHER"))

	for _, e := range h.FromManifests() {
		switch strings.ToLower(e.GameID) {
		case "launcher", "repo", "_registry":
			t.Errorf("%q was listed as a game", e.GameID)
		}
	}
	if got := len(h.FromManifests()); got != 1 {
		t.Fatalf("scan found %d games, want only real-game: %+v", got, h.FromManifests())
	}
}

// Files next to the manifest directories are not games either.
func TestLooseFilesAreNotGames(t *testing.T) {
	root := withManifestDirs(t, "a-game")
	if err := os.WriteFile(filepath.Join(root, "manifests", "notes.txt"), []byte("x"), 0o600); err != nil {
		t.Fatal(err)
	}
	if got := New(root).FromManifests(); len(got) != 1 || got[0].GameID != "a-game" {
		t.Fatalf("scan returned %+v", got)
	}
}

// The order must be stable: os.ReadDir order is not guaranteed across platforms,
// and an unstable list makes the admin's game list jump between reloads.
func TestScanIsSortedAndStable(t *testing.T) {
	h := New(withManifestDirs(t, "zeta", "alpha", "mid"))

	items := decodeItems(t, h.Scan, httptest.NewRequestWithContext(t.Context(), http.MethodGet, "/admin/api/games/scan", nil))
	if len(items) != 3 {
		t.Fatalf("scan returned %d games", len(items))
	}
	for i := 1; i < len(items); i++ {
		if items[i-1].GameID > items[i].GameID {
			t.Fatalf("scan is not sorted: %+v", items)
		}
	}
}

// An absent manifests directory is a fresh install, not an error.
func TestScanOnEmptyServerReturnsEmptyList(t *testing.T) {
	items := decodeItems(t, New(t.TempDir()).Scan, httptest.NewRequestWithContext(t.Context(), http.MethodGet, "/admin/api/games/scan", nil))
	if len(items) != 0 {
		t.Fatalf("scan on an empty server returned %+v", items)
	}
}

// Scan must not overwrite what the admin has already saved: it is a "what is on
// disk" probe, and the stored registry carries hand-entered titles and exe paths.
func TestScanDoesNotTouchTheStoredRegistry(t *testing.T) {
	root := withManifestDirs(t, "a-game")
	h := New(root)
	saveRegistry(t, h, []Entry{{GameID: "a-game", Title: "Моя игра", ExeRelativePath: "bin/game.exe"}})

	decodeItems(t, h.Scan, httptest.NewRequestWithContext(t.Context(), http.MethodGet, "/admin/api/games/scan", nil))

	items := decodeItems(t, h.Get, httptest.NewRequestWithContext(t.Context(), http.MethodGet, "/admin/api/games", nil))
	if len(items) != 1 || items[0].Title != "Моя игра" {
		t.Fatalf("scan clobbered the stored registry: %+v", items)
	}
}

// A saved registry round-trips with every field intact. ExeRelativePath in
// particular is what the launcher runs — losing it makes the Play button do nothing.
func TestSavedRegistryRoundTrips(t *testing.T) {
	h := New(t.TempDir())
	want := []Entry{
		{GameID: "lethal-company", Title: "Lethal Company", ExeRelativePath: "Lethal Company.exe", IconURL: "/manifests/lethal-company/icon.png"},
		{GameID: "raft", Title: "Рафт", ExeRelativePath: "Raft.exe"},
	}
	saveRegistry(t, h, want)

	got := decodeItems(t, h.Get, httptest.NewRequestWithContext(t.Context(), http.MethodGet, "/admin/api/games", nil))
	if len(got) != len(want) {
		t.Fatalf("registry holds %d entries, want %d", len(got), len(want))
	}
	for i := range want {
		if got[i] != want[i] {
			t.Errorf("entry %d round-tripped as %+v, want %+v", i, got[i], want[i])
		}
	}
}

// Saving replaces the list rather than merging: removing a game from the panel
// must actually remove it.
func TestSaveReplacesTheWholeList(t *testing.T) {
	h := New(t.TempDir())
	saveRegistry(t, h, []Entry{{GameID: "a"}, {GameID: "b"}})
	saveRegistry(t, h, []Entry{{GameID: "a"}})

	if got := decodeItems(t, h.Get, httptest.NewRequestWithContext(t.Context(), http.MethodGet, "/admin/api/games", nil)); len(got) != 1 {
		t.Fatalf("registry holds %d entries after removing one: %+v", len(got), got)
	}
}

// Save is a mutation and must not be reachable by GET: the admin API is
// cookie-authenticated, and a GET mutation is triggerable from any page.
func TestSaveRejectsGet(t *testing.T) {
	w := httptest.NewRecorder()
	New(t.TempDir()).Save(w, httptest.NewRequestWithContext(t.Context(), http.MethodGet, "/admin/api/games/save", nil))
	if w.Code == http.StatusOK {
		t.Fatal("Save accepted a GET")
	}
}

// A malformed body must be refused, and the stored registry left alone — the
// launcher reads this file through the public API.
func TestSaveRejectsGarbageWithoutDamagingTheRegistry(t *testing.T) {
	h := New(t.TempDir())
	saveRegistry(t, h, []Entry{{GameID: "a", Title: "хорошая запись"}})

	w := httptest.NewRecorder()
	r := httptest.NewRequestWithContext(t.Context(), http.MethodPost, "/admin/api/games/save", strings.NewReader("не json"))
	h.Save(w, r)
	if w.Code != http.StatusBadRequest {
		t.Fatalf("Save accepted garbage: %d", w.Code)
	}

	got := decodeItems(t, h.Get, httptest.NewRequestWithContext(t.Context(), http.MethodGet, "/admin/api/games", nil))
	if len(got) != 1 || got[0].Title != "хорошая запись" {
		t.Fatalf("the registry was damaged by a rejected save: %+v", got)
	}
}

// An empty list is a legitimate state (all games removed) and must be storable.
func TestEmptyRegistryIsStorable(t *testing.T) {
	h := New(t.TempDir())
	saveRegistry(t, h, []Entry{})
	if got := decodeItems(t, h.Get, httptest.NewRequestWithContext(t.Context(), http.MethodGet, "/admin/api/games", nil)); len(got) != 0 {
		t.Fatalf("registry holds %+v, want empty", got)
	}
}

// saveRegistry posts a list and fails the test if it is not stored.
func saveRegistry(t *testing.T, h *Handlers, items []Entry) {
	t.Helper()
	body, err := json.Marshal(struct {
		Items []Entry `json:"items"`
	}{Items: items})
	if err != nil {
		t.Fatal(err)
	}
	w := httptest.NewRecorder()
	r := httptest.NewRequestWithContext(t.Context(), http.MethodPost, "/admin/api/games/save", strings.NewReader(string(body)))
	h.Save(w, r)
	if w.Code != http.StatusOK {
		t.Fatalf("Save returned %d: %s", w.Code, w.Body.String())
	}
}

// A bad gameId must be refused AT THE SAVE, not quietly dropped when the public
// API reads the file later.
//
// Every id in the registry becomes a path component. The reader does drop
// unusable ones, but dropping is a silent cure: a typo made the game vanish
// from the launcher while the panel still said "saved", and the operator had no
// way to connect the two. Refusing the write names the offending entry at once.
func TestSaveRejectsUnsafeGameID(t *testing.T) {
	for _, bad := range []string{"../../etc", "bad id", "", "a/b", "game.id", "игра"} {
		h := New(t.TempDir())
		body, err := json.Marshal(struct {
			Items []Entry `json:"items"`
		}{Items: []Entry{{GameID: "ok-game"}, {GameID: bad}}})
		if err != nil {
			t.Fatal(err)
		}

		w := httptest.NewRecorder()
		r := httptest.NewRequestWithContext(t.Context(), http.MethodPost, "/admin/api/games/save", strings.NewReader(string(body)))
		h.Save(w, r)

		if w.Code != http.StatusBadRequest {
			t.Errorf("Save accepted gameId %q with %d", bad, w.Code)
			continue
		}
		// Nothing may be written: a partially applied save would drop the valid
		// entry the operator sent alongside the bad one.
		if _, err := os.Stat(filepath.Join(h.root, "manifests", "_registry", "games.json")); err == nil {
			t.Errorf("gameId %q was refused but the registry was written anyway", bad)
		}
	}
}

// The refusal must name which entry is wrong — the panel shows this text, and
// "invalid gameId" alone is useless when the operator sent a dozen games.
func TestSaveRefusalPointsAtTheEntry(t *testing.T) {
	h := New(t.TempDir())
	body, err := json.Marshal(struct {
		Items []Entry `json:"items"`
	}{Items: []Entry{{GameID: "fine"}, {GameID: "also-fine"}, {GameID: "../evil"}}})
	if err != nil {
		t.Fatal(err)
	}

	w := httptest.NewRecorder()
	h.Save(w, httptest.NewRequestWithContext(t.Context(), http.MethodPost, "/admin/api/games/save", strings.NewReader(string(body))))

	if !strings.Contains(w.Body.String(), "3") {
		t.Fatalf("the refusal does not say which entry failed: %q", w.Body.String())
	}
}
