package builds

import (
	"net/http"
	"net/http/httptest"
	"net/url"
	"os"
	"path/filepath"
	"testing"
)

// Every endpoint that turns a gameId/version pair into a path must reject
// traversal input, not just DeleteVersion.
func TestListVersionsRejectsUnsafeGameID(t *testing.T) {
	h := New(t.TempDir())
	for _, gid := range []string{"../secret", "a/b", `..\secret`} {
		w := httptest.NewRecorder()
		r := httptest.NewRequest(http.MethodGet,
			"http://example.com/admin/api/list?gameId="+url.QueryEscape(gid), nil)
		h.ListVersions(w, r)
		if w.Code != http.StatusBadRequest {
			t.Errorf("ListVersions(%q) = %d, want 400", gid, w.Code)
		}
	}
}

func TestActivateRejectsUnsafeInput(t *testing.T) {
	root := t.TempDir()
	h := New(root)
	// A manifest that a traversal attempt could otherwise reach.
	outside := filepath.Join(root, "secret")
	if err := os.MkdirAll(outside, 0o755); err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(filepath.Join(outside, "1.0.0.json"), []byte(`{}`), 0o644); err != nil {
		t.Fatal(err)
	}
	cases := []struct{ gid, ver string }{
		{"../secret", "1.0.0"},
		{"game", "../../evil"},
		{"game", "a/b"},
	}
	for _, tc := range cases {
		w := httptest.NewRecorder()
		r := httptest.NewRequest(http.MethodPost,
			"http://example.com/admin/api/activate?gameId="+url.QueryEscape(tc.gid)+"&version="+url.QueryEscape(tc.ver), nil)
		h.Activate(w, r)
		if w.Code != http.StatusBadRequest {
			t.Errorf("Activate(%q,%q) = %d, want 400", tc.gid, tc.ver, w.Code)
		}
	}
	if _, err := os.Stat(filepath.Join(outside, "latest.json")); err == nil {
		t.Fatal("Activate wrote latest.json outside the manifests tree")
	}
}

// uploadId is generated by the server and is joined into a filesystem path by
// every chunked handler; a client-supplied non-hex value must never get there.
func TestChunkedHandlersRejectUnsafeUploadID(t *testing.T) {
	h := New(t.TempDir())
	h.CurrentUser = func(*http.Request) string { return "admin" }

	bad := []string{"../../etc", "..", "a/b", "zzzz-not-hex", "", "abc"}
	handlers := map[string]struct {
		fn     http.HandlerFunc
		method string
	}{
		"status":   {h.UploadStatus, http.MethodGet},
		"complete": {h.UploadComplete, http.MethodPost},
		"process":  {h.UploadProcessStream, http.MethodPost},
		"chunk":    {h.UploadChunk, http.MethodPut},
	}
	for name, hd := range handlers {
		for _, id := range bad {
			w := httptest.NewRecorder()
			r := httptest.NewRequest(hd.method,
				"http://example.com/admin/api/upload/"+name+"?uploadId="+url.QueryEscape(id)+"&index=0", nil)
			hd.fn(w, r)
			if w.Code != http.StatusBadRequest {
				t.Errorf("%s(uploadId=%q) = %d, want 400", name, id, w.Code)
			}
		}
	}
}

// The processing endpoint publishes a build, so it must not be reachable with a
// method the CSRF check ignores.
func TestUploadProcessStreamRequiresPost(t *testing.T) {
	h := New(t.TempDir())
	h.CurrentUser = func(*http.Request) string { return "admin" }
	for _, m := range []string{http.MethodGet, http.MethodHead} {
		w := httptest.NewRecorder()
		h.UploadProcessStream(w, httptest.NewRequest(m,
			"http://example.com/admin/api/upload/process?uploadId=0123456789abcdef0123456789abcdef", nil))
		if w.Code != http.StatusMethodNotAllowed {
			t.Errorf("%s process = %d, want 405", m, w.Code)
		}
	}
}

func TestUploadIDAcceptsGeneratedIDs(t *testing.T) {
	r := httptest.NewRequest(http.MethodGet, "http://example.com/x?uploadId=0123456789abcdef0123456789abcdef", nil)
	if id, ok := uploadID(r); !ok || id != "0123456789abcdef0123456789abcdef" {
		t.Fatalf("uploadID rejected a server-generated id: %q %v", id, ok)
	}
}
