// Package httpx holds the HTTP middleware both ChillHub servers share: request
// logging, cache headers, request ids, CORS, Prometheus metrics and the listen
// address resolution.
package httpx

import (
	"crypto/rand"
	"encoding/hex"
	"encoding/json"
	"fmt"
	"log"
	"net/http"
	"strings"
	"time"
)

// loggingResponseWriter captures status code.
type loggingResponseWriter struct {
	http.ResponseWriter

	status int
}

func (lrw *loggingResponseWriter) WriteHeader(statusCode int) {
	lrw.status = statusCode
	lrw.ResponseWriter.WriteHeader(statusCode)
}

// Flush forwards to the underlying ResponseWriter if it implements http.Flusher.
func (lrw *loggingResponseWriter) Flush() {
	if f, ok := lrw.ResponseWriter.(http.Flusher); ok {
		f.Flush()
	}
}

// Logging returns middleware that logs method, url, status and duration with an
// optional label prefix.
func Logging(label string) func(http.Handler) http.Handler {
	return func(next http.Handler) http.Handler {
		return http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
			start := time.Now()
			lrw := &loggingResponseWriter{ResponseWriter: w, status: http.StatusOK}
			next.ServeHTTP(lrw, r)
			log.Print(logLine(label, r, lrw.status, time.Since(start))) // #nosec G706 -- logLine escapes/validates every client-controlled field, see below.
		})
	}
}

// logLine assembles one access-log record.
//
// Every field here is either generated by the server or already safe to print:
// the method is validated by net/http before a handler ever runs, URL.String()
// re-encodes the request target so a percent-escaped newline stays escaped, and
// the request id goes through sanitizeRequestID — the raw header is what a
// client controls, and Logging may run without the RequestID middleware in
// front of it, so it must not be trusted here either.
func logLine(label string, r *http.Request, status int, dur time.Duration) string {
	var b strings.Builder
	if label != "" {
		b.WriteString(label)
		b.WriteByte(' ')
	}
	fmt.Fprintf(&b, "%s %s %d %s", r.Method, r.URL.String(), status, dur)
	if reqID := sanitizeRequestID(r.Header.Get("X-Request-Id")); reqID != "" {
		b.WriteString(" reqid=")
		b.WriteString(reqID)
	}
	return b.String()
}

// Revalidate marks a response as cacheable but always checked with the origin.
//
// Static pictures — game icons, news covers, hero art — change rarely and weigh
// tens of kilobytes each. Under NoStore a client had to download every one of
// them on every launch, because "no-store" forbids keeping the bytes at all.
// With this header the client keeps the bytes and asks a conditional question
// instead: http.FileServer answers 304 Not Modified from Last-Modified, so an
// unchanged picture crosses the wire once and never again — while a replaced
// one still arrives immediately, since every request is revalidated.
//
// This is deliberately NOT used for manifests: those decide which version a
// client installs, and there a stale answer costs a wrong installation.
func Revalidate(h http.Handler) http.Handler {
	return http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		w.Header().Set("Cache-Control", "public, max-age=0, must-revalidate")
		h.ServeHTTP(w, r)
	})
}

// NoStore adds headers to disable caching.
func NoStore(h http.Handler) http.Handler {
	return http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		w.Header().Set("Cache-Control", "no-store")
		w.Header().Set("Pragma", "no-cache")
		w.Header().Set("Expires", "0")
		h.ServeHTTP(w, r)
	})
}

// maxRequestIDLen bounds an incoming X-Request-Id.
const maxRequestIDLen = 64

// sanitizeRequestID returns the caller's request id if it is safe to keep, or
// "" if a fresh one should be generated.
//
// The value ends up in every log line for the request and is echoed back in a
// response header, and it is entirely attacker-controlled: without a bound a
// client can pad the access log with kilobytes per request, and with control
// characters it can forge log lines (a newline plus a fake entry) or smuggle
// terminal escapes into whatever reads the log. Only a short, printable ASCII
// identifier is accepted.
func sanitizeRequestID(v string) string {
	v = strings.TrimSpace(v)
	if v == "" || len(v) > maxRequestIDLen {
		return ""
	}
	for i := range len(v) {
		c := v[i]
		switch {
		case c >= 'a' && c <= 'z', c >= 'A' && c <= 'Z', c >= '0' && c <= '9':
		case c == '-', c == '_', c == '.', c == ':':
		default:
			return ""
		}
	}
	return v
}

// RequestID middleware: ensures each request has an X-Request-Id header
// (a sane incoming value is preserved, anything else is replaced).
func RequestID() func(http.Handler) http.Handler {
	return func(next http.Handler) http.Handler {
		return http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
			rid := sanitizeRequestID(r.Header.Get("X-Request-Id"))
			if rid == "" {
				// generate 16 random bytes as hex (32 chars)
				var b [16]byte
				if _, err := rand.Read(b[:]); err == nil {
					rid = hex.EncodeToString(b[:])
				} else {
					rid = time.Now().UTC().Format("20060102150405.000000000")
				}
				r = r.Clone(r.Context())
				r.Header.Set("X-Request-Id", rid)
			}
			w.Header().Set("X-Request-Id", rid)
			next.ServeHTTP(w, r)
		})
	}
}

// CORSDisabled is the origin spec that turns cross-origin access off entirely.
// Preflight requests are still answered (so they never reach the handlers),
// but no Access-Control-* headers are emitted, which keeps the API same-origin.
const CORSDisabled = "none"

// CORS adds CORS headers according to the given origin spec, which may be:
//   - "*"                 allow any origin (cookies are not usable cross-site)
//   - "none" / "off"      emit no CORS headers at all (same-origin only)
//   - "a.example,b.example" comma-separated allow-list of exact origins; a
//     matching request Origin is echoed back and credentials are allowed
//
// An empty spec keeps the historical "*" behaviour.
func CORS(origin string) func(http.Handler) http.Handler {
	policy := parseCORSPolicy(origin)
	return func(next http.Handler) http.Handler {
		return http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
			policy.apply(w, r)
			// Preflight is answered here so that OPTIONS never reaches a mutating handler.
			if r.Method == http.MethodOptions {
				w.WriteHeader(http.StatusNoContent)
				return
			}
			next.ServeHTTP(w, r)
		})
	}
}

// corsPolicy is the parsed form of a CORS origin spec. Parsing once, outside
// the handler, keeps the per-request path to a single switch.
type corsPolicy struct {
	disabled  bool
	wildcard  bool
	allowList []string
}

// parseCORSPolicy interprets the origin spec documented on CORS.
func parseCORSPolicy(origin string) corsPolicy {
	spec := strings.TrimSpace(origin)
	if spec == "" {
		spec = "*"
	}
	p := corsPolicy{
		disabled: strings.EqualFold(spec, CORSDisabled) || strings.EqualFold(spec, "off"),
		wildcard: spec == "*",
	}
	if p.disabled || p.wildcard {
		return p
	}
	for o := range strings.SplitSeq(spec, ",") {
		if o = strings.TrimSpace(o); o != "" {
			p.allowList = append(p.allowList, o)
		}
	}
	return p
}

// apply writes the Access-Control-* headers this policy allows for r.
func (p corsPolicy) apply(w http.ResponseWriter, r *http.Request) {
	if p.disabled {
		// No CORS headers at all; the preflight short-circuit still applies.
		return
	}
	if p.wildcard {
		w.Header().Set("Access-Control-Allow-Origin", "*")
		w.Header().Set("Vary", "Origin")
	} else {
		p.echoAllowedOrigin(w, r)
	}
	w.Header().Set("Access-Control-Allow-Methods", "GET,POST,PUT,PATCH,DELETE,OPTIONS")
	w.Header().Set("Access-Control-Allow-Headers", "*, Authorization, Content-Type, X-Requested-With, X-Request-Id")
	w.Header().Set("Access-Control-Expose-Headers", "X-Request-Id, Content-Length")
}

// echoAllowedOrigin echoes the request Origin back only when it is on the
// allow-list. An exact echo is what makes cookie-authenticated calls possible,
// which is exactly why an arbitrary Origin must never reach this header.
func (p corsPolicy) echoAllowedOrigin(w http.ResponseWriter, r *http.Request) {
	reqOrigin := strings.TrimSpace(r.Header.Get("Origin"))
	w.Header().Set("Vary", "Origin")
	for _, o := range p.allowList {
		if strings.EqualFold(o, reqOrigin) {
			w.Header().Set("Access-Control-Allow-Origin", reqOrigin)
			w.Header().Set("Access-Control-Allow-Credentials", "true")
			return
		}
	}
}

// WriteJSON writes value as application/json with no-store headers.
//
// v is an any, so encoding can genuinely fail (a channel, a func, a cycle) —
// and it fails AFTER the 200 and part of the body are already on the wire, so
// there is nothing left to answer with. Swallowing the error silently left no
// trace at all of a handler shipping a half-written response; it now reaches the
// journal, where the truncated JSON on the client side can be explained.
func WriteJSON(w http.ResponseWriter, v any) {
	w.Header().Set("Content-Type", "application/json")
	w.Header().Set("Cache-Control", "no-store")
	w.Header().Set("Pragma", "no-cache")
	w.Header().Set("Expires", "0")
	if err := json.NewEncoder(w).Encode(v); err != nil {
		log.Printf("[httpx] encode json response: %v", err)
	}
}

// BaseURL builds external base URL honoring X-Forwarded-* headers.
func BaseURL(r *http.Request) string {
	proto := strings.TrimSpace(r.Header.Get("X-Forwarded-Proto"))
	if proto == "" {
		if r.TLS != nil {
			proto = "https"
		} else {
			proto = "http"
		}
	}
	host := strings.TrimSpace(r.Header.Get("X-Forwarded-Host"))
	if host == "" {
		host = r.Host
	}
	port := strings.TrimSpace(r.Header.Get("X-Forwarded-Port"))
	if port != "" && !strings.Contains(host, ":") {
		if (proto != "http" || port != "80") && (proto != "https" || port != "443") {
			host = host + ":" + port
		}
	}
	return proto + "://" + host
}
